// Temporarily disabled Supabase client to prevent connection errors during MySQL migration
// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// Disable Supabase temporarily during migration
console.warn('Supabase client is temporarily disabled during MySQL migration');

// Mock the supabase client to prevent errors in components that still reference it
export const supabase = {
  from: () => ({
    select: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
    insert: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
    update: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
    delete: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
    upsert: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
  }),
  auth: {
    getUser: () => ({ data: { user: null }, error: new Error('Supabase disabled during migration') }),
    signOut: () => ({ error: new Error('Supabase disabled during migration') }),
  },
  storage: {
    from: () => ({
      upload: () => ({ data: null, error: new Error('Supabase disabled during migration') }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    }),
  },
};

// Disable all the settings functions that use Supabase
export const getAppSettings = async () => {
  console.warn('getAppSettings disabled during MySQL migration');
  return null;
};

export const saveAppSettings = async (settings: any) => {
  console.warn('saveAppSettings disabled during MySQL migration');
  return { success: false, error: 'Supabase disabled during migration' };
};

export const initializeApp = async () => {
  console.warn('initializeApp disabled during MySQL migration');
  return null;
};

// Remove event listener
// if (typeof window !== 'undefined') {
//   window.addEventListener('DOMContentLoaded', () => {
//     initializeApp();
//   });
// }
